### ISSUE TITLE
PWD_Vault.bat does not initialize in Windows

### ISSUE THREAD

**Issue by fernandoleira** [nightmare-tech/PWD_Vault#15]
I'm trying to run the `PWD_Vault.bat` file on my Windows PC to start PWD_Vault, but the CMD Terminal is not being displayed. I currently have Python 3.10.7 installed with Windows 10 Pro.

**Comment by nightmare-tech** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/73050725/193492520-dd2e9128-5787-48e9-ad9c-8e3f6fdc97f4.png">
Its working for me. This was newly cloned. Send a screenshot or screen recording

**Comment by fernandoleira** [comment]
Sorry for the delay. I fixed this problem by re-installing pip and the project dependencies. Closing this issue.
