### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by mohakgupt** [nightmare-tech/PWD_Vault#16]
According to Hactoberfest guidelines it is important to have contributing.md in your repo. Please assign this to me.

**Comment by nightmare-tech** [comment]
please send screenshot of the guideline

**Comment by nightmare-tech** [comment]
Or the link to the guidelines

**Comment by nightmare-tech** [comment]
I read the guideline. That is for the maintainer to do.

**Comment by nightmare-tech** [comment]
I will do it today

**Comment by mohakgupt** [comment]
> please send screenshot of the guideline

**Comment by nightmare-tech** [comment]
Since you have made it, I will merge your PR.

**Comment by mohakgupt** [comment]
> Since you have made it, I will merge your PR.

Thanks
