### ISSUE TITLE
anyone with access to system can read passwords without knowing master password

### ISSUE THREAD

**Issue by theCasm** [nightmare-tech/PWD_Vault#18]
The program only uses the master password for verification, not encryption. The actual encryption key is stored on disk, so anyone can use it to view passwords.

For convenience, you can simply edit the program slightly. Replacing line 61 in endecrypt.py with `check_pwd = True` will allow a user to use the program regardless of what they enter for the master password.

The program should base the encryption key off of the master password and ***not*** store it. Whenever the program is run, it would first verify the password the same way and then, if correct, regenerate the key using the inputted password.

**Comment by nightmare-tech** [comment]
You want to work on it? Then I'll create a beta branch

**Comment by theCasm** [comment]
Sure, I'll see what I can do

**Comment by nightmare-tech** [comment]
I have asked on discord for the same. But users say it's not possible to do this locally as they will have to store the encryption key to decrypt/encrypt again and I agree, but can happen remotely which I don't have the resources for.

**Comment by theCasm** [comment]
should be fixed with #19
